/*
 *  Copyright (C) 2011 Peter Zotov <whitequark@whitequark.org>
 *  JZ4750 GPIO pin definitions
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under  the terms of the GNU General Public License as published by the
 *  Free Software Foundation;  either version 2 of the License, or (at your
 *  option) any later version.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#ifndef __ASM_MACH_JZ4750_GPIO_H__
#define __ASM_MACH_JZ4750_GPIO_H__

#include <asm/mach-jz47xx/gpio.h>

/* Port C function pins */
#define JZ_GPIO_LCD_DATA0		JZ_GPIO_PORTD(0)
#define JZ_GPIO_LCD_DATA1		JZ_GPIO_PORTD(1)
#define JZ_GPIO_LCD_DATA2		JZ_GPIO_PORTD(2)
#define JZ_GPIO_LCD_DATA3		JZ_GPIO_PORTD(3)
#define JZ_GPIO_LCD_DATA4		JZ_GPIO_PORTD(4)
#define JZ_GPIO_LCD_DATA5		JZ_GPIO_PORTD(5)
#define JZ_GPIO_LCD_DATA6		JZ_GPIO_PORTD(6)
#define JZ_GPIO_LCD_DATA7		JZ_GPIO_PORTD(7)
#define JZ_GPIO_LCD_DATA8		JZ_GPIO_PORTD(8)
#define JZ_GPIO_LCD_DATA9		JZ_GPIO_PORTD(9)
#define JZ_GPIO_LCD_DATA10		JZ_GPIO_PORTD(10)
#define JZ_GPIO_LCD_DATA11		JZ_GPIO_PORTD(11)
#define JZ_GPIO_LCD_DATA12		JZ_GPIO_PORTD(12)
#define JZ_GPIO_LCD_DATA13		JZ_GPIO_PORTD(13)
#define JZ_GPIO_LCD_DATA14		JZ_GPIO_PORTD(14)
#define JZ_GPIO_LCD_DATA15		JZ_GPIO_PORTD(15)
#define JZ_GPIO_LCD_DATA16		JZ_GPIO_PORTD(16)
#define JZ_GPIO_LCD_DATA17		JZ_GPIO_PORTD(17)
#define JZ_GPIO_LCD_PCLK		JZ_GPIO_PORTD(18)
#define JZ_GPIO_LCD_HSYNC		JZ_GPIO_PORTD(19)
#define JZ_GPIO_LCD_VSYNC		JZ_GPIO_PORTD(20)
#define JZ_GPIO_LCD_DE			JZ_GPIO_PORTD(21)

#define JZ_GPIO_LCD_CLS			JZ_GPIO_PORTD(22)
#define JZ_GPIO_LCD_SPL			JZ_GPIO_PORTD(23)
#define JZ_GPIO_LCD_PS			JZ_GPIO_PORTD(24)
#define JZ_GPIO_LCD_REV			JZ_GPIO_PORTD(25)

#define JZ_GPIO_FUNC_LCD_DATA0		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA1		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA2		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA3		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA4		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA5		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA6		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA7		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA8		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA9		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA10		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA11		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA12		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA13		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA14		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA15		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA16		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DATA17		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_PCLK		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_VSYNC		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_HSYNC		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_DE		JZ_GPIO_FUNC1

#define JZ_GPIO_FUNC_LCD_CLS		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_SPL		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_PS		JZ_GPIO_FUNC1
#define JZ_GPIO_FUNC_LCD_REV		JZ_GPIO_FUNC1

#endif
