
obj-y += clock.o platform.o time.o gpio.o irq.o pwm.o

obj-$(CONFIG_JZ4740_QI_LB60)	+= board-qi_lb60.o
obj-$(CONFIG_JZ4740_N516)	+= board-n516.o board-n516-display.o
obj-$(CONFIG_JZ4740_N526)	+= board-n526.o
obj-$(CONFIG_JZ4740_ID800WT)	+= board-id800wt.o


